GET http://localhost:7500/api/article
###YES

GET http://localhost:7500/api/article/website/5a0cb0da43df22dafd240c7dc177771595726858
###YES

GET http://localhost:7500/api/article/category/eb40898470f9fc303bb1f5f27ef351084a6f272
###YES

GET http://localhost:7500/api/article/02cf4e7db732159f19123a90d22f2fda857fac77
###YES

DELETE http://localhost:7500/api/article/01cba42d50a9878a77cc4dc4fea919369223acc6
###YES

PUT http://localhost:7500/api/article/02cf4e7db732159f19123a90d22f2fda857fac77
Content-Type: application/json

{
    "title": "Afghanistan : les Taliban annoncent \"une amnistie\" pour les employés d'État",
    "pageLink": "https://www.france24.com/fr/asie-pacifique/20210817-afghanistan-les-taliban-annoncent-une-amnistie-pour-les-employ%C3%A9s-d-%C3%A9tat",
    "imageLink": "https://google.com",
    "contentBase": "Afghanistan : les Taliban annoncent \"une amnistie\" pour les employés d'État",
    "date": "2021-08-18 18:08:47",
    "categorieToken": "8276cf21cd12cc93bfe3159ef286f0f775e1318b",
    "webSiteToken": "5a0cb0da43df22dafd240c7dc177771595726858"
}
###
