GET http://localhost:7500/api/website
###YES

GET http://localhost:7500/api/website/328ae4c2d4b20b0663074b54259c43e79f82fd44
###

DELETE http://localhost:7500/api/website/f5adaf0a0b302d0e87bc4594a2d17d75f2fbf854
###

POST http://localhost:7500/api/website
Content-Type: application/json

{
    "name" : "Otacku Attack 4",
    "indexPageLink" : "http://localhost:82"
}
###

PUT http://localhost:7500/api/website/noirnoirnoir
Content-Type: application/json

{
    "token" : "d82c9e0ce14138114ad9f5900bc5424c5f2f864c",
    "name" : "goldDigger api",
    "indexPageLink" : "http://localhost:7500"
}
###
